server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:projectDB;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
  h2:
    console:
      enabled: true
      path: /h2-console

gcp:
  config:
    file: gcp-account-file.json
  project:
    id: imposing-pipe-356718
  bucket:
    id: media-bucket-007
  dir:
    name: dev

logging:
  level:
    org.springframework: ERROR
    com.app: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log
